name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "deploy.sh"
        target: "~/"

    - name: SSH into EC2 and run deploy.sh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          chmod +x deploy.sh
          export GITHUB_USER=${{ secrets.GITHUB_USER }}
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ./deploy.sh
